export * from "./types"
export * from "./config"
export * from "./personalize"
export * from "./brand"
export { sendEmail, emailService, isTransientEmailError } from "./service"
export type { EmailServiceSendOptions } from "./service"
export { renderWaitlistWelcome } from "./templates/waitlist-welcome"
export { getEmailProvider } from "./providers/registry"
